### ISSUE TITLE
HTTP Error 403: Forbidden - When trying to run the training part (on mnist.yml file)

### ISSUE THREAD

**Issue by AmanK1202** [monniert/dti-clustering#2] opened 2021-03-08 17:11 UTC
I am running the entire experiment on Google Colab (after setting up all the required environments).
On running the line:

**! source activate dtic && cuda=gpu_id config=mnist.yml tag=run_tag ./pipeline.sh**

I get the following error:

[2021-03-08 16:43:28] Trainer initialisation: run directory is /content/dti-clustering/runs/mnist/0308_run_tag
[2021-03-08 16:43:28] Config /content/dti-clustering/configs/mnist.yml copied to run directory
[2021-03-08 16:43:28] Using cpu device, nb_device is None
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to /content/dti-clustering/datasets/MNIST/raw/train-images-idx3-ubyte.gz
0it [00:00, ?it/s]Traceback (most recent call last):
  File "src/trainer.py", line 617, in <module>
    trainer = Trainer(config, run_dir, seed=seed)
  File "/content/dti-clustering/src/utils/__init__.py", line 102, in wrapper
    return f(*args, **kw)
  File "src/trainer.py", line 72, in __init__
    train_dataset = get_dataset(self.dataset_name)("train", **self.dataset_kwargs)
  File "/content/dti-clustering/src/dataset/torchvision.py", line 40, in __init__
    dataset = self.dataset_class(root=self.root, transform=self.transform, download=True, **kwargs)
  File "/usr/local/envs/dtic/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 70, in __init__
    self.download()
  File "/usr/local/envs/dtic/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 137, in download
    download_and_extract_archive(url, download_root=self.raw_folder, filename=filename, md5=md5)
  File "/usr/local/envs/dtic/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 249, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/usr/local/envs/dtic/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 83, in download_url
    raise e
  File "/usr/local/envs/dtic/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 71, in download_url
    reporthook=gen_bar_updater()
  File "/usr/local/envs/dtic/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/envs/dtic/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/envs/dtic/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/envs/dtic/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/envs/dtic/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/envs/dtic/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/envs/dtic/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
0it [00:00, ?it/s]

**Comment by monniert** [comment] 2021-03-10 17:21
Hi @AmanK1202, as described in the logs, this error has nothing to do with the training pipeline, it is a HTTP issue (e.g. it can be a proxy that blocks http requests) which prevents you from downloading MNIST dataset from pytorch servers. 

I suggest you try debugging the error by downloading the dataset with:
```
from torchvision.datasets import MNIST
dataset = MNIST(root='.', download=True)
```

or you can download it by other means (e.g. manually) and move it to 'dti-clustering/datasets/MNIST'

**Comment by AmanK1202** [comment] 2021-03-30 20:00
Hello,

Thanks for your response. The problem was with the mnist data set and it
got resolved.
I was going through your paper in detail and was wondering, have you used a
tailor-made loss function for your DTI_kmeans module? Is this because you
wanted to incorporate a loss function (with transformation of prototypes).
Awaiting your response.

Best regards,
Amn Kumar

**Comment by monniert** [comment] 2021-04-06 16:15
Hi @AmanK1202, we have tried other losses for DTI Kmeans (L1 distance or SSIM) but both gave worse results compared to classical squared L2 distance as used in the Kmeans algorithm

**Comment by monniert** [comment] 2021-05-14 12:48
I suppose the issue is fixed so I close it for now, please reopen if needed

**Closed as completed by monniert** 2021-05-14 12:48 UTC

**Comment by AmanK1202** [comment] 2021-05-14 13:12
Yes sure. Thanks for the help.

Regards,
Aman Kumar
